# Generated by Django 2.1 on 2018-11-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='buastatus',
            new_name='bugstatus',
        ),
    ]
